image: Visual Studio 2017

configuration: Release

platform:
  - x64

install:
  - nuget restore
build:
  project: Engine.sln

before_test:
  - echo -----------------------ABOUT TO RUN TEST.EXE---------------------------------

test_script:
  - cmd: "%APPVEYOR_BUILD_FOLDER%\Temporary\Tests_%Platform%_%Configuration%\Tests.exe"

after_test:
  - echo -----------------------DONE RUNNING TEST.EXE-----------------------------------
